# Generated by Django 4.0.2 on 2022-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0003_meal_updated_variety_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='variety',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
