# Generated by Django 4.0.2 on 2022-02-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0004_alter_meal_slug_alter_variety_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='menu',
            field=models.TextField(default='a'),
        ),
    ]
