# Generated by Django 4.0.2 on 2022-03-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart_code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
