# Generated by Django 4.0.2 on 2022-03-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0004_alter_shipping_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='spice',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='admin_remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
